version: "3.8"

services:
  db:
    container_name: dsek-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dsek
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  meilisearch:
    container_name: dsek-meilisearch
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
    ports:
      - "7700:7700"
    volumes:
      - ./data.ms:/data.ms

volumes:
  db:
    driver: local
