name: Release build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js latest LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "pnpm"
      - run: pnpm i
      - run: pnpm run build

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip build

      - uses: softprops/action-gh-release@v2
        with:
          files: build.zip

      - shell: bash
        env: 
          JENKINS_DEPLOY_TOKEN: ${{ secrets.JENKINS_DEPLOY_TRIGGER }}
        run: |
          curl -L "jenkins.dsek.se/buildByToken/build?job=Deploy_web&token=$JENKINS_DEPLOY_TOKEN"
